name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: write-all

jobs:
  test:
    name: 'Code quality and test'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.6]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest pytest-cov
          if [ -f src/requirements-dev.txt ]; then pip install -r src/requirements-dev.txt; fi
      - name: Static Code Linting with ruff
        run: |
          # default set of ruff rules with GitHub Annotations
          ruff --format=github --target-version=py37 .
        continue-on-error: true
      - name: Test with pytest
        run: |
          pytest --cov-config=.coveragerc --cov-report term --cov-report html:htmlcov --cov=src tests
      - name: Upload code coverage html report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: htmlcov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}